"""Add missing location_type column

Revision ID: 78cb393d087b
Revises: 
Create Date: 2025-09-22 23:38:42.229842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cb393d087b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('od_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('od_requests', schema=None) as batch_op:
        batch_op.drop_column('location_type')

    # ### end Alembic commands ###
